In [2]:
import numpy as np
import pandas as pd

Q1. FIND THE PANDAS VERSION

In [3]:
np.__version__

'2.5.3'

In [4]:
pd.__version__

'3.0.6'

In [33]:
url = 'https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv?utm_source=chatgpt.com'

In [34]:
df = pd.read_csv(url)

In [35]:
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

Q2. RECORDS COUNT

In [36]:
df.shape[0]

10000

Q3. FUEL TYPES

In [37]:
df['fuel_type'].nunique()

3

Q4. MISSING VALUES

In [38]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

Q5. MAX FUEL EFFICIENCY

In [39]:
df['fuel_efficiency_mpg'].max()

np.float64(41.2)

Q6. MEDIAN VALUE OF HORSEPOWER

In [40]:
median_bfr = df['horsepower'].median()
median_bfr

np.float64(254.0)

In [41]:
mode_horsepower = df['horsepower'].mode()[0]
mode_horsepower

np.float64(252.0)

In [42]:
df['horsepower'] = df['horsepower'].fillna(mode_horsepower)

In [43]:
median_aftr = df['horsepower'].median()
median_aftr

np.float64(252.0)

In [44]:
print(median_bfr)
print(median_aftr)

254.0
252.0

The median of the Horsepower has decreased.

Q7. SUM OF WEIGHTS

In [45]:
asia_cars = df[df['origin'] == 'Asia']

In [46]:
asia_cars = asia_cars[['vehicle_weight', 'model_year']]

In [47]:
asia_cars = asia_cars.head(7)

In [48]:
asia_cars

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [49]:
X = asia_cars.values

In [50]:
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [51]:
XTX = X.T @ X

In [52]:
XTX_inv = np.linalg.inv(XTX)

In [53]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [54]:
w = XTX_inv @ X.T @ y

In [55]:
w.sum()

np.float64(0.36919696904925486)

In [56]:
np.sum(w)

np.float64(0.36919696904925486)

THE END